#!/usr/bin/env bash
# bash script that transfers a file from our client to a server
if [$# -lt 4]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    ssh -o StrictHostKeyChecking=no -i $4 $3@$2 "mkdir -p ~/"
    scp -i $4 -o StrictHostKeyChecking=no $1 $3@$2:~/
fi

