#!/usr/bin/env bash
# Configuring load balancer with haproxy.

apt-get update
apt-get install -y haproxy

echo "frontend http
        bind *:80
        mode http
        default_backend backend-servers

backend backend-servers
        balance roundrobin
        mode http
        option forwardfor
        server 292997-web-01 35.175.64.48:80 check
        server 292997-web-02 52.205.215.101:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
